### ISSUE TITLE
Wifi connection ?

### ISSUE THREAD

**Issue by attilatheprogramer** [SimonRafferty/Webasto-Heater---Replacement-Controller#1]
Hello, i didn’t find code for wifi connection setup and what is possible to make with this connection that you specified on pcb

**Comment by SimonRafferty** [comment]
You're right!
Unfortunately, I discovered that you cannot use WiFi & Analog read at the same time on an ESP32 - the WiFi messes up the ADC.

I later changed to the M0 processor - which doesn't have WiFi at all, but has a better Analog implementation.

**Comment by attilatheprogramer** [comment]
Ah is it right thanks for response

SimonRafferty ***@***.***> (időpont: 2022. jan. 8., Szo,
14:16) ezt írta:
