### ISSUE TITLE
Petrol Thermo Top C possible?

### ISSUE THREAD

**Issue by menotuu** [SimonRafferty/Webasto-Heater---Replacement-Controller#10]
Can this board work with a petrol based Thermo Top C too possibly?

**Comment by SimonRafferty** [comment]
Short answer - Yes!
Longer answer - the air-fuel mixture will need to be edited.  So it will require a bit of experimentation.

The way I originally found the air-fuel mixture for the diesel version was to measure the fan speed (using an optical rpm meter with a painted white mark on the fan) and by timing the fuel-pump pulses using the stock controller.

For the startup routine, I copied this exactly.  Once the heater was running, I just needed the ratio of fan rpm to fuel pulses per minute.  So long as the ratio stays roughly the same, it will stay alight!

Then I used a cheapo Carbon Monoxide detector to tune the mixtures for the minimum CO.

**Comment by menotuu** [comment]
1. is a [LOLIN ESP-WROOM-32](https://www.wemos.cc/en/latest/d32/d32.html) good enough? I know I have to use only adc1 pins, it have 6 of them and have to edit the pcb a bit for that board because some Pins are different.
2. on webastardo v3 in Arduino ide 2.2.2 I receive error in line 217
'restart_timer' was not declared in this scope


can you help me later after soldering the pcb to bring it to live with petrol?

the thing is, the stock controller is notable to run, because its VW canbus controlled (Thermo top c petrol 2013).

**Comment by menotuu** [comment]
and 3. are the pcb text prints reversed for water therm and exhaust therm?
because the code says
```
int water_temp_pin = A1;        // exhaust temp? pcb text says goes to pin 3 
int exhaust_temp_pin = A2;      // water temp? pcb text says goes to pin 5
```
is only the pcb print reversed?

4. whats does Analog IP 03 mean? is this lambda_pin for future?

sorry I only want to understand it all correctly before burning hardware.

![Uploading Screenshot 2023-12-12 132029.png…]()

**Comment by SimonRafferty** [comment]
On the board, there is a 6 pin connector - the same as the original Webasto board.

The Pin numbers refer to that, not the pins on the processor.

So, pin 3 on the connector goes to A1 on the microprocessor

**Comment by SimonRafferty** [comment]
Closed

**Comment by menotuu** [comment]
misunderstood.
Pin 3 goes to A1 via R11 4k7 divider for exhaust temp. right
And pin 5 goes to the A2 via R12 100k divider and is for exhaust pin too. 
I know, either this or this. because pcb text says use r11 or r12 divider.

But in the code A1 is for water temp sensor, and the text on the pcb on left side claims that too.
