### ISSUE TITLE
Adding support for the M4

### ISSUE THREAD

**Issue by prensel** [SimonRafferty/Webasto-Heater---Replacement-Controller#2]
Hi, I have ordered some pcb's by JLCPCB and want to start tinkering with adding CANbus support. My plan is to use the Feather M4 CAN Express.
A nice option would be the alter the routing for the pins 2 and 3 to have it selectable to either the CANbus pins of the M4 or the current pins A0 and A3.

**Comment by SimonRafferty** [comment]
> A nice option would be the alter the routing for the pins 2 and 3 to have it selectable to either the CANbus pins of the M4 or the current pins A0 and A3.

I'd not considered that - mainly because the original controllers (some of them) are CAN controlled - and one possible use case for this is to remove the requirement for CAN.
You could just fork the PCB design to implement that?  Then it leaves other people with the option.
